image: node:latest

stages:
  - test

server:
  stage: test
  tags:
    - linux
  script:
    - cd ./server/
    - npm install
    - npm coverage

client:
  stage: test
  tags:
    - linux
  script:
    - cd ./client/
    - npm install
    - npm coverage