image: node:latest

stages:
  - test

server:
  stage: test
  tags:
    - linux
  script:
    - cd ./server/
    - npm ci
    - npm run coverage

client:
  stage: test
  tags:
    - linux
  script:
    - cd ./client/
    - npm ci
    - npm run coverage