image: node:12.16.1

stages:
  - test
  - release

server:
  stage: test
  tags:
    - linux
  script:
    - cd ./server/
    - npm ci
    - npm run lint
    - npm run coverage

client:
  stage: test
  tags:
    - linux
  script:
    - cd ./client/
    - npm ci
    - npm run lint
    - npm run coverage

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  when: manual
  # We recommend the use of `except: tags` to prevent these pipelines
  # from running. See the notes section below for details.
  tags:
    - linux
  script:
    - cd scripts
    - sudo ./build.sh
    - release-cli create --name "v1.0.0" --description "Tis is a new release of 18.30" --tag-name "v1.0.0" --ref $CI_COMMIT_SHA


